version: '3'

services:
  nuxt:
    container_name: nuxt_app

    build:
      context: .
      dockerfile: Dockerfile

    image: nuxt_app_image

    volumes:
      - .:/app

    tty: true

    command: npm start

    ports:
      - "9000:9000"

    environment:
      - NODE_ENV=environment-1
